apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-catalog
  template:
    metadata:
      labels:
        app: image-catalog
    spec:
      containers:
        - image: mzakel/image-catalog:2023-01-04-21-06-17
          name: image-catalog
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://dumbo.db.elephantsql.com:5432/tfzmcoxl
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: tfzmcoxl
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-images
                  key: password
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: image-catalog
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: image-catalog
